### ISSUE TITLE
NULL on AutoIncrement ID when reference used

### ISSUE THREAD

**Issue by vertisan** [hautelook/AliceBundle#508] opened 2020-07-24 10:20 UTC
Hi,  
I have some entities:  
```php
class FirstEntity
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\Column(name="id", type="integer")
     */
    protected int $id;

    public function getId(): int
    {
        return $this->id;
    }

    // ....
}

class SecondEntity
{
    protected int $firstEntityId;

    public function __construct(FirstEntity $firstEntity)
    {
        $this->firstEntityId = $firstEntity->getId();
    }
    // ....
}
```
and fixtures for it:  
```yaml
App\Entity\FirstEntity:
  first_{1..10}:

App\Entity\SecondEntity:
  second_{1..10}:
    __construct:
      - '@first_<current()>'
```

When I tried to load these fixtures, I'm getting error:  
```
Typed property App\Entity\FirstEntity::$id must not be accessed before initialization
```
How objects from fixtures are loaded and how to resolve this problem?

**Comment by theofidry** [comment] 2020-08-17 13:52
Closing as a duplicate of https://github.com/nelmio/alice/issues/1045 to which I already answered

**Closed by theofidry** 2020-08-17 13:52 UTC
