### ISSUE TITLE
Unable to load fixtures following the new README.md file

### ISSUE THREAD

**Issue by gitmehubb** [hautelook/AliceBundle#284] opened 2016-11-07 10:41 UTC
First, the _doctrine/orm-bundle_ package provided in the "Example of installation:", as here:

```bash
composer require --dev hautelook/alice-bundle:^2.0@dev \
  theofidry/alice-data-fixtures:^1.0@dev \
  doctrine/orm-bundle \
  doctrine/orm:^2.5 \
  doctrine/data-fixtures
```
is not a valid package. Should we remove it?

But the issue is more about the loading of fixtures that is not working when following the new README.md file : it is written that we should indicate:

```yaml
# app/config/config_dev.yml

hautelook_alice:
    fixtures_path: 'Resources/fixtures/orm' # Path to which to look for fixtures relative to the bundle path.
```

Nothing happens when executing the doctrine command `php app/console hautelook:fixtures:load`

So I tried to use the previous configuration:

```yaml
# app/config/config_dev.yml

hautelook_alice:
    db_drivers:
        orm: ~          # Enable Doctrine ORM if is registered
        mongodb: ~      # Enable Doctrine ODM if is registered
        phpcr: ~        # Enable Doctrine PHPCR ODM if is registered
    locale: en_US       # Locale to used for faker; must be a valid Faker locale otherwise will fallback to en_US
    seed: 1             # A seed to make sure faker generates data consistently across runs, set to null to disable
    persist_once: false # Only persist objects once if multiple files are passed
    loading_limit: 5    # Maximum number of time the loader will try to load the files passed
```

but after launching the doctrine command, I get the following errors:
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]                         
  Unrecognized options "db_drivers, locale, seed, persist_once, loading_limit" under "hautelook_alice"

Can you please review?

Best Regards,

**Comment by theofidry** [comment] 2016-11-07 10:49
Hey @gitmehubb,

Thanks for the bug report, the 2.x version is still on beta so a bit rough on the edges so any feedback like this is a help.

>the doctrine/orm-bundle package provided [...] is not a valid package. Should we remove it?

Not sure what you mean by "not valid". If you mean you already have it in `require`, then yes it is redundant you don't need to add it to `require-dev` as well.

>But the issue is more about the loading of fixtures that is not working when following the new README.md file : it is written that we should indicate:

This more interesting. There is a few tests on that one so it's probably something I missed. Do you have a repository you could show or give access to so that I can debug it? Otherwise could you share your file structure (i.e. where are your fixtures located)?

Is it a migration or a brand new project?

>So I tried to use the previous configuration:

Yes no that won't work 😛

**Comment by gitmehubb** [comment] 2016-11-07 12:56
> Not sure what you mean by "not valid"

launching the following command:
````bash
composer require --dev doctrine/orm-bundle
````
we get:
````bash
[InvalidArgumentException]                                                                                                                     
Could not find package doctrine/orm-bundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
````

> Do you have a repository you could show or give access to so that I can debug it? [...] Is it a migration or a brand new project?

Basically I am starting a new Symfony project (v3.1.5) and I followed the README.md file. I created the Dummy and RelatedDummy entities (after the following command:
````bash
doctrine:schema:update --force 
````
my tables were created)

But once I launch: `php app/console hautelook:fixtures:load`, no fixtures (within "Resources/fixtures/orm") are found and so they are not loaded.

**Comment by theofidry** [comment] 2016-11-07 12:59
Ah, its `doctrine/doctrine-bundle` not `doctrine/orm-bundle` :facepalm:

>But once I launch: php app/console hautelook:fixtures:load, no fixtures (within "Resources/fixtures/orm") are found and so they are not loaded.

Weird as I'm sure to have tested that :thinking:. Oh well, will sort that out tonight

**Comment by gitmehubb** [comment] 2016-11-07 13:42
Pour info, sous "require-dev:" j'ai :

````json
"hautelook/alice-bundle": "~2.0@dev",
"doctrine/data-fixtures": "~1.2.1",
"nelmio/alice": "~3.0.0@dev",
"theofidry/alice-data-fixtures": "~1.0@dev"
````

**Comment by theofidry** [comment] 2016-11-08 00:04
Hm works for me if I put my fixture files in `app/Resources/fixtures/orm` but it doesn't if I put them in `src/AppBundle/Resources/fixtures/orm`

**Comment by theofidry** [comment] 2016-11-08 00:12
Maybe you could try to debug `Hautelook\AliceBundle\Loader\DoctrineOrmLoader` (the locateFixtures bit).

**Comment by theofidry** [comment] 2016-11-08 21:11
Ah, also note that I had to use the verbose mode to see the fixture files loaded, that *is* a bug.

**Comment by gitmehubb** [comment] 2016-11-17 15:03
I launched the command to load the fixtures and I got the following info
````bash
[datetime] app.INFO: fixtures found {"files":[]} 
[datetime] app.INFO: fixtures loaded 
```` end

Is that normal to get the "files" variable to empty?

Pour information : I am using Symfony v3 (are you also using the v3?)

Regards,

**Comment by theofidry** [comment] 2016-11-17 15:56
@gitmehubb yes I am using Symfony 3.x, is it possible to have more info on your project?

If I can have access to it it would be way easier, I'm open to sign an NDA if it's a private project as well. Otherwise I would need the following:

- your `composer.json`
- the result of `composer show -i`
- your `AppKernel`
- your PHP version
- your config related to nelmio/alice, theofidry/alice-data-fixtures, hautelook/alice-bundle
- the location of your fixture files
- the command you're using

Sorry if that sounds like a lot, I just prefer to ask an exhaustive list of what can help rather than needless back and forth.

**Comment by mariouriarte** [comment] 2016-12-17 21:43
hello, I have the same problem
This is my $ composer show -i
doctrine/annotations                 v1.2.7        Docblock Annotations Parser
doctrine/cache                       v1.6.1        Caching library offering an object-oriented API ...
doctrine/collections                 v1.3.0        Collections Abstraction library
doctrine/common                      v2.6.1        Common Library for Doctrine projects
doctrine/data-fixtures               v1.2.2        Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        v2.5.5        Database Abstraction Layer
doctrine/doctrine-bundle             1.6.4         Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.0         Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle    2.3.0         Symfony DoctrineFixturesBundle
doctrine/inflector                   v1.1.0        Common String Manipulations with regard to casin...
doctrine/instantiator                1.0.5         A small, lightweight utility to instantiate obje...
doctrine/lexer                       v1.0.1        Base library for a lexer that can be used in Top...
doctrine/orm                         v2.5.5        Object-Relational-Mapper for PHP
fzaninotto/faker                     v1.6.0        Faker is a PHP library that generates fake data ...
hautelook/alice-bundle               v2.0.0-beta.3 Symfony2 Bundle to manage fixtures with Alice an...
incenteev/composer-parameter-handler v2.1.2        Composer script handling your ignored parameter ...
jdorn/sql-formatter                  v1.2.17       a PHP SQL highlighting library
monolog/monolog                      1.22.0        Sends your logs to files, sockets, inboxes, data...
myclabs/deep-copy                    1.5.5         Create deep copies (clones) of your objects
nelmio/alice                         v3.0.0-beta.3 Expressive fixtures generator
paragonie/random_compat              v2.0.4        PHP 5.x polyfill for random_bytes() and random_i...
psr/cache                            1.0.1         Common interface for caching libraries
psr/log                              1.0.2         Common interface for logging libraries
sensio/distribution-bundle           v5.0.14       Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.16       This bundle provides a way to configure your con...
sensio/generator-bundle              v3.1.1        This bundle generates code for you
sensiolabs/security-checker          v4.0.0        A security checker for your composer.lock
swiftmailer/swiftmailer              v5.4.4        Swiftmailer, free feature-rich PHP mailer
symfony/monolog-bundle               3.0.1         Symfony MonologBundle
symfony/phpunit-bridge               v3.2.0        Symfony PHPUnit Bridge
symfony/polyfill-apcu                v1.3.0        Symfony polyfill backporting apcu_* functions to...
symfony/polyfill-intl-icu            v1.3.0        Symfony polyfill for intl's ICU-related data and...
symfony/polyfill-mbstring            v1.3.0        Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.3.0        Symfony polyfill backporting some PHP 5.6+ featu...
symfony/polyfill-php70               v1.3.0        Symfony polyfill backporting some PHP 7.0+ featu...
symfony/polyfill-util                v1.3.0        Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle           v2.4.0        Symfony SwiftmailerBundle
symfony/symfony                      v3.2.0        The Symfony PHP framework
theofidry/alice-data-fixtures        v1.0.0-beta.4 Nelmio alice extension to persist the loaded fix...
twig/twig                            v1.28.2       Twig, the flexible, fast, and secure template la...
---
### AppKernel
<?php

use Symfony\Component\HttpKernel\Kernel;
use Symfony\Component\Config\Loader\LoaderInterface;

class AppKernel extends Kernel
{
    public function registerBundles()
    {
        $bundles = [
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new AppBundle\AppBundle(),
        ];

        if (in_array($this->getEnvironment(), ['dev', 'test'], true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
            $bundles[] = new Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle();

            $bundles[] = new Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle();
            $bundles[] = new Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle();
            $bundles[] = new Hautelook\AliceBundle\HautelookAliceBundle();
        }

        return $bundles;
    }

    public function getRootDir()
    {
        return __DIR__;
    }

    public function getCacheDir()
    {
        return dirname(__DIR__).'/var/cache/'.$this->getEnvironment();
    }

    public function getLogDir()
    {
        return dirname(__DIR__).'/var/logs';
    }

    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load($this->getRootDir().'/config/config_'.$this->getEnvironment().'.yml');
    }
}
---
### PHP version
php -v
PHP 7.0.13 (cli) (built: Nov  9 2016 16:21:40) ( NTS )
---
###  location of my fixture files
/cupon/app/Resources/fixtures/orm/Ciudad.yml
---
### command im using
php bin/console hautelook:fixtures:load -vvv
Careful, database will be purged. Do you want to continue y/N ?y
[2016-12-17 17:40:48] app.INFO: fixtures found {"files":[]} 
[2016-12-17 17:40:48] app.INFO: fixtures loaded  
---
config_dev.yml
imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com
hautelook_alice:
    fixtures_path: 'Resources/fixtures/orm' # Path to which to look for fixtures relative to the bundle path.

am i bad?

**Comment by theofidry** [comment] 2016-12-17 21:51
@mariouriarte would you mind formatting your post correctly? I can't ready it as it is...

**Comment by mariouriarte** [comment] 2016-12-17 21:52
ok

**Comment by theofidry** [comment] 2016-12-17 21:57
I think it's related to #296

**Comment by mariouriarte** [comment] 2016-12-17 21:59
do it my friend

**Comment by vetal2409** [comment] 2016-12-19 12:43
DoctrineOrmLoader scans files only in the bundles but not in the **app** folder
`$fixtureFiles = $this->fixtureLocator->locateFiles($bundles, $environment);`

Just move your **fixtrures** folder to Resources of any bundle and it will work well!)

**Comment by theofidry** [comment] 2016-12-19 12:44
Yep, closing as it's a duplicate of #296. For now moving files as @vetal2409 works fine, but I want to add support for `app/Resources` as Symfony tends to get towards a bundle-less standard edition.

**Closed by theofidry** 2016-12-19 12:44 UTC
Labels: Blocked, bug
