### ISSUE TITLE
Nested functions not working

### ISSUE THREAD

**Issue by sourcerer-mike** [hautelook/AliceBundle#327] opened 2017-03-12 20:54 UTC
Alice describes something like:

    '<strtolower(<(implode(" ", ["HELLO", "WORLD", \<foo()>]))>)> \<bar()>'

But hautelook:fixtures:load says:

> The value "<(implode(" "" contains an unclosed function.

This occurs in a yml like this:

```
Foo\BarEntity:
  message_{1..29}:
    title: <text(50)>
    level: '<strtolower(<(implode(" ", ["HELLO", "WORLD", \<foo()>]))>)> \<bar()>'
  message_{30..100}:
    title: <text(50)>
    level: '<strtolower(<(implode(" ", ["HELLO", "WORLD", \<foo()>]))>)> \<bar()>'
```

Example taken from https://github.com/nelmio/alice/blob/master/doc/advanced-guide.md#functions
Also for simpler things like `'<pow(0,<numberBetween(0,2)>)>'` .

**Comment by theofidry** [comment] 2017-03-12 21:35
Duplicate of https://github.com/nelmio/alice/issues/663.

Sorry for the inconvenience, the quick fix is to patch the Lexer in alice... the proper fix is to take care of https://github.com/nelmio/alice/issues/601.

**Closed by theofidry** 2017-03-12 21:35 UTC
