### ISSUE TITLE
Load fixtures in a specific order

### ISSUE THREAD

**Issue by oenie** [hautelook/AliceBundle#469] opened 2019-04-15 15:45 UTC
I am trying to work with Doctrine and the Alice bundle but have run into a circular dependency problem of some sort.

It's kind of hard to see where this is happening, I have tried the reordering as per the 
[Advanced usage](https://github.com/hautelook/AliceBundle/blob/master/doc/advanced-usage.md#persisting-the-classes-in-a-specific-order) but that does not seem to help.

It gives me a different order than when the persisting actually happens. I suspect thisis due the 'automatic fixing of circular references' ? If so, it seems to me that something is wrong in some situations. 

The fixtures that seem to be giving me the headache are the ones with a __construct method that needs the arguments for FK constraints like below:

```yaml
AppBundle\Entity\SignLocation:
    signLocation (template):
        active: true
        tenant: '@tenant1'
        location: <geoPointBelgium()>

    signLocation1 (extends signLocation):
        __construct: ['@sign1', '@parkingBanIntake1']
```

In this case the `@Sign1` reference is not yet loaded when the `SignLocation` entity is being persisted, resulting a `NULL` value constraint violation (because `sign_id` in its table has a non null constraint) 

Is there a way (as is mentioned in the Doctrine fixtures manual) to signal that a certain object relies on another one ? Excuse me if this issue is a bit vague, I will try to provide more information if needed :)

**Comment by oenie** [comment] 2019-04-15 15:48
Composer output for reference:

anahkiasen/underscore-php            2.0.0                              A redacted port of Underscore.js for PHP
behat/transliterator                 v1.2.0                             String transliterator
composer/ca-bundle                   1.1.4                              Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
ddeboer/data-import                  0.18.0                             Import data from, and export data to, a range of file formats and media
doctrine/annotations                 v1.6.1                             Docblock Annotations Parser
doctrine/cache                       v1.8.0                             Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.6.1                             PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      v2.10.0                            PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, persistence interfaces, proxies, event sy...
doctrine/data-fixtures               v1.3.1                             Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        v2.9.2                             Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle             1.10.2                             Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.5                              Symfony Bundle for Doctrine Cache
doctrine/doctrine-migrations-bundle  v1.3.2                             Symfony DoctrineMigrationsBundle
doctrine/event-manager               v1.0.0                             Doctrine Event Manager component
doctrine/inflector                   v1.3.0                             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                1.2.0                              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       v1.0.1                             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  v1.8.1                             Database Schema migrations using Doctrine DBAL
doctrine/orm                         v2.6.3                             Object-Relational-Mapper for PHP
doctrine/persistence                 v1.1.0                             The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                  v1.0.0                             Doctrine Reflection component
elasticsearch/elasticsearch          v6.1.0                             PHP Client for Elasticsearch
fig/link-util                        1.0.0                              Common utility implementations for HTTP links
friendsofsymfony/elastica-bundle     dev-master 4f830ed                 Elasticsearch PHP integration for your Symfony project using Elastica
friendsofsymfony/oauth-server-bundle 1.6.2                              Symfony2 OAuth Server Bundle
friendsofsymfony/oauth2-php          1.2.3                              OAuth2 library
friendsofsymfony/rest-bundle         2.5.0                              This Bundle provides various tools to rapidly develop RESTful API's with Symfony
friendsofsymfony/user-bundle         v2.1.2                             Symfony FOSUserBundle
fzaninotto/faker                     v1.8.0                             Faker is a PHP library that generates fake data for you.
gedmo/doctrine-extensions            v2.4.37                            Doctrine2 behavioral extensions
geocoder-php/plugin                  1.1.0                              Plugins to Geocoder providers
giggsey/libphonenumber-for-php       8.10.8                             PHP Port of Google's libphonenumber
giggsey/locale                       1.6                                Locale functions required by libphonenumber-for-php
guzzlehttp/guzzle                    6.3.3                              Guzzle is a PHP HTTP client library
guzzlehttp/promises                  v1.3.1                             Guzzle promises library
guzzlehttp/psr7                      1.5.2                              PSR-7 message implementation that also provides common utility methods
guzzlehttp/ringphp                   1.1.1                              Provides a simple API and specification that abstracts away the details of HTTP into a single PHP function.
guzzlehttp/streams                   3.0.0                              Provides a simple abstraction over streams of data
hautelook/alice-bundle               v2.4.1                             Symfony bundle to manage fixtures with Alice and Faker.
hoa/compiler                         3.17.08.08                         The Hoa\Compiler library.
hoa/consistency                      1.17.05.02                         The Hoa\Consistency library.
hoa/event                            1.17.01.13                         The Hoa\Event library.
hoa/exception                        1.17.01.16                         The Hoa\Exception library.
hoa/file                             1.17.07.11                         The Hoa\File library.
hoa/iterator                         2.17.01.10                         The Hoa\Iterator library.
hoa/math                             1.17.05.16                         The Hoa\Math library.
hoa/protocol                         1.17.01.14                         The Hoa\Protocol library.
hoa/regex                            1.17.01.13                         The Hoa\Regex library.
hoa/stream                           1.17.02.21                         The Hoa\Stream library.
hoa/ustring                          4.17.01.16                         The Hoa\Ustring library.
hoa/visitor                          2.17.01.16                         The Hoa\Visitor library.
hoa/zformat                          1.17.01.10                         The Hoa\Zformat library.
incenteev/composer-parameter-handler v2.1.3                             Composer script handling your ignored parameter file
jdorn/sql-formatter                  v1.2.17                            a PHP SQL highlighting library
jmikola/geojson                      1.0.2                              GeoJSON implementation for PHP
jms/metadata                         2.0.0                              Class/method/property metadata management in PHP
jms/serializer                       2.2.0                              Library for (de-)serializing data of any complexity; supports XML, JSON, and YAML.
jms/serializer-bundle                3.2.0                              Allows you to easily serialize, and deserialize data of any complexity
jms/translation-bundle               1.4.3                              Puts the Symfony Translation Component on steroids
jsor/doctrine-postgis                v1.7.0                             Spatial and Geographic Data with PostGIS and Doctrine.
knplabs/doctrine-behaviors           1.6.0                              Doctrine2 behavior traits
knplabs/knp-snappy                   v1.1.0                             PHP5 library allowing thumbnail, snapshot or PDF generation from a url or a html page. Wrapper for wkhtmltopdf/wkhtmltoimage.
knplabs/knp-snappy-bundle            v1.6.0                             Easily create PDF and images in Symfony2 by converting Twig/HTML templates.
kriswallsmith/assetic                v1.4.0                             Asset Management for PHP
liuggio/ExcelBundle                  v2.1.0                             This is a Symfony2 Bundle helps you to read and write Excel files (including pdf, xlsx, odt), thanks to the PHPExcel library
michelf/php-markdown                 1.8.0                              PHP Markdown
monolog/monolog                      1.24.0                             Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                    1.8.1                              Create deep copies (clones) of your objects
nelmio/alice                         v3.4.1                             Expressive fixtures generator
nelmio/api-doc-bundle                2.13.3                             Generates documentation for your REST API from annotations
nelmio/cors-bundle                   1.5.5                              Adds CORS (Cross-Origin Resource Sharing) headers support in your Symfony2 application
nikic/php-parser                     v4.2.1                             A PHP parser written in PHP
ocramius/package-versions            1.4.0                              Composer plugin that provides efficient querying for installed package versions (no runtime IO)
ocramius/proxy-manager               2.2.2                              A library providing utilities to generate, instantiate and generally operate with Object Proxies
pagerfanta/pagerfanta                v1.1.0                             Pagination for PHP 5.3
paragonie/random_compat              v2.0.18                            PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
patchwork/utf8                       v1.3.1                             Portable and performant UTF-8, Unicode and Grapheme Clusters for PHP
phar-io/manifest                     1.0.1                              Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                      1.0.1                              Library for handling version information and constraints
phayes/geophp                        1.2                                GeoPHP is a open-source native PHP library for doing geometry operations. It is written entirely in PHP and can therefore run on shared hosts. It can read and write a wide variety of formats: WKT...
php-amqplib/php-amqplib              v2.9.1                             Formerly videlalvaro/php-amqplib.  This library is a pure PHP implementation of the AMQP protocol. It's been tested against RabbitMQ.
php-amqplib/rabbitmq-bundle          v1.9.0                             Integrates php-amqplib with Symfony2 and RabbitMq. Formerly oldsound/rabbitmq-bundle.
php-http/promise                     v1.0.0                             Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common      1.0.1                              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    4.3.0                              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver          0.4.0
phpoffice/phpexcel                   1.8.2                              PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpspec/prophecy                     1.8.0                              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage            5.3.2                              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator            1.4.5                              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template            1.2.1                              Simple template engine.
phpunit/php-timer                    1.0.9                              Utility class for timing
phpunit/php-token-stream             2.0.2                              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                      6.5.14                             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects         5.0.10                             Mock Object library for PHPUnit
proj4php/proj4php                    2.0.10                             A PHP-Class for geographic coordinates transformation using proj4 definitions, thanks to a translation from Proj4JS
psr/cache                            1.0.1                              Common interface for caching libraries
psr/container                        1.0.0                              Common Container Interface (PHP FIG PSR-11)
psr/http-message                     1.0.1                              Common interface for HTTP messages
psr/link                             1.0.0                              Common interfaces for HTTP links
psr/log                              1.1.0                              Common interface for logging libraries
psr/simple-cache                     1.0.1                              Common interfaces for simple caching
ralouphie/getallheaders              2.0.5                              A polyfill for getallheaders.
ramsey/uuid                          3.8.0                              Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
react/promise                        v2.7.1                             A lightweight implementation of CommonJS Promises/A for PHP
ronanguilloux/isocodes               2.1.5                              PHP library - Validators for standards from ISO, International Finance, Public Administrations, GS1, Book and Music Industries, Phone numbers & Zipcodes for many countries
ruflin/elastica                      6.1.1                              Elasticsearch Client
sebastian/code-unit-reverse-lookup   1.0.1                              Looks up which function or method a line of code belongs to
sebastian/comparator                 2.1.3                              Provides the functionality to compare PHP values for equality
sebastian/diff                       2.0.1                              Diff implementation
sebastian/environment                3.1.0                              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   3.1.0                              Provides the functionality to export PHP variables for visualization
sebastian/global-state               2.0.0                              Snapshotting of global state
sebastian/object-enumerator          3.0.3                              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector           1.1.1                              Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context          3.0.0                              Provides functionality to recursively process PHP variables
sebastian/resource-operations        1.0.0                              Provides a list of PHP built-in functions that operate on resources
sebastian/version                    2.0.1                              Library that helps with managing the version number of Git-hosted PHP projects
sensio/distribution-bundle           v5.0.24                            Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v5.2.4                             This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v3.1.7                             This bundle generates code for you
sensiolabs/security-checker          v5.0.3                             A security checker for your composer.lock
swiftmailer/swiftmailer              v5.4.12                            Swiftmailer, free feature-rich PHP mailer
symfony/assetic-bundle               v2.8.2                             Integrates Assetic into Symfony2
symfony/monolog-bundle               v3.3.1                             Symfony MonologBundle
symfony/polyfill-apcu                v1.11.0                            Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype               v1.11.0                            Symfony polyfill for ctype functions
symfony/polyfill-intl-icu            v1.11.0                            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.11.0                            Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.11.0                            Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70               v1.11.0                            Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72               v1.11.0                            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util                v1.11.0                            Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle           v2.6.7                             Symfony SwiftmailerBundle
symfony/symfony                      v3.4.24                            The Symfony PHP framework
theofidry/alice-data-fixtures        v1.1.1                             Nelmio alice extension to persist the loaded fixtures.
theseer/tokenizer                    1.1.2                              A small library for converting tokenized PHP source code into XML and potentially other formats
twig/twig                            v1.37.1                            Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                     1.4.0                              Assertions to validate method input/output with nice error messages.
willdurand/geocoder                  4.2.1                              Common files for PHP Geocoder
willdurand/geocoder-bundle           5.3.0                              Integration of Geocoder into Symfony
willdurand/jsonp-callback-validator  v1.1.0                             JSONP callback validator.
willdurand/negotiation               v2.3.1                             Content Negotiation tools for PHP provided as a standalone library.
yohang/finite                        1.1.2
zendframework/zend-code              3.3.1
zendframework/zend-eventmanager      3.2.1

**Comment by oenie** [comment] 2019-04-15 16:19
The strange thing is that I resolved some of the problems by moving all fixtures in the same yaml file. When I start pulling them apart, things go bad for those entities as well.

**Comment by theofidry** [comment] 2019-05-04 20:28
>In this case the @Sign1 reference is not yet loaded when the SignLocation entity is being persisted, resulting a NULL value constraint violation (because sign_id in its table has a non null constraint)

This seems a bit weird to me: the way alice works is:

- parse & interpret & combine the files into fixtures
- create the objects from the fixtures
- persist the fixtures (persit all and then a flush by default)

So even if `@signLocation1` is being instantiated by alice before `@sign1`, alice will notice the dependence and create `@sign1` first.

**Comment by theofidry** [comment] 2019-05-04 20:28
It might be related to https://github.com/nelmio/alice/pull/963 though

**Comment by theofidry** [comment] 2021-02-23 09:27
Since the related issue has been merged I hope this has been fixed. If note please open a new issue with a reproducer

**Closed by theofidry** 2021-02-23 09:27 UTC
